### PR TITLE
Install Splunk in the layer then repack tgz of etc to allow upgrade.

### PR DESCRIPTION
**Pull request by mikedickey**
Fixing merge conflicts in Ryan Faircloth's fork that installs everything from splunk package except etc, and rebuilds the package so that it only includes etc, to support faster startup without sacraficing upgrades.

### CODE REVIEW

**Comment by arctan5x** [comment]
Hey Mike, would you verify if /opt/splunk is completely owned by the user "splunk" after this change?

**Review by lephino — COMMENTED** [review]
I think we need a way to also know that you "need" to upgrade. Since we unpack, I think we should copy version.txt back to /tmp, and on startup maybe we add an ansible play to copy version.txt to SPLUNK_HOME/var.  Then if they don't match, we know the user automatically should be upgraded.

**Comment by lephino** [comment]
also, do we really want the full size of splunk + tar splunk?  Probably at this point just better to go back to the old container, untar, backup etc / var, and on startup copy them back on top.

**Comment by SkyKnightSKS** [comment]
Using https://github.com/splunk/splunk-ansible/pull/100 we are able to see if we need to upgrade.
When this is combined with https://github.com/splunk/docker-splunk/pull/123 and https://github.com/splunk/splunk-ansible/pull/103 we know which version we currently are, which we are going to upgrade to and if we need an upgrade.

**Comment by arctan5x** [comment]
@mikedickey Hi Mike. Is this PR still valid and waiting for review?

**Comment by mikedickey** [comment]
This PR is no longer relevant, replaced by https://github.com/splunk/docker-splunk/pull/127

**Pull request closed without merging**
